name: Run apply-py.py

on:
  schedule:
    - cron: '0,30 0-7 * * *'  # every 30 minutes between 8AM and 3PM UTC+8
  workflow_dispatch:  # allows manual trigger
  push:
    branches: [main]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies (if needed)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        env:
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
        run: |
          python apply-py.py

